// Room navigation database for BU campus map
// Floor codes: B/G = below grade, N = main/entry level, 1-9 = upper floors

export const FLOOR_INFO = {
  B: { label: 'Basement',        stairs: 'Head down to the basement level' },
  G: { label: 'Ground Floor',    stairs: 'Head down to the ground floor' },
  N: { label: 'Main Floor',      stairs: 'The room is on the main (entry) floor — no stairs needed' },
  1: { label: '1st Floor',       stairs: 'The room is on the 1st floor — no stairs needed' },
  2: { label: '2nd Floor',       stairs: 'Take the stairs or elevator up to the 2nd floor' },
  3: { label: '3rd Floor',       stairs: 'Take the stairs or elevator up to the 3rd floor' },
  4: { label: '4th Floor',       stairs: 'Take the stairs or elevator up to the 4th floor' },
  5: { label: '5th Floor',       stairs: 'Take the stairs or elevator up to the 5th floor' },
  6: { label: '6th Floor',       stairs: 'Take the elevator up to the 6th floor' },
  7: { label: '7th Floor',       stairs: 'Take the elevator up to the 7th floor' },
  8: { label: '8th Floor',       stairs: 'Take the elevator up to the 8th floor' },
  9: { label: '9th Floor',       stairs: 'Take the elevator up to the 9th floor' },
};

// Each room: { id, floor, type, desc }
// floor matches a key in FLOOR_INFO
export const ROOMS = {

  // ── Academic A (Bldg 069) ───────────────────────────────────────────
  AA: [
    // Ground floor
    { id: 'G01',  floor: 'G', type: 'classroom', desc: 'Large classroom (1,818 sf)' },
    { id: 'G01B', floor: 'G', type: 'classroom', desc: 'Classroom (1,219 sf)' },
    { id: 'G01K', floor: 'G', type: 'classroom', desc: 'Classroom' },
    { id: 'G05',  floor: 'G', type: 'classroom', desc: 'Classroom (1,055 sf)' },
    { id: 'G06',  floor: 'G', type: 'office',    desc: 'Office (590 sf)' },
    { id: 'G07',  floor: 'G', type: 'classroom', desc: 'Large classroom (1,603 sf)' },
    { id: 'G08',  floor: 'G', type: 'classroom', desc: 'Classroom (2,417 sf)' },
    { id: 'G10',  floor: 'G', type: 'classroom', desc: 'Classroom (770 sf)' },
    { id: 'G12',  floor: 'G', type: 'classroom', desc: 'Classroom (348 sf)' },
    { id: 'G14',  floor: 'G', type: 'classroom', desc: 'Classroom (492 sf)' },
    { id: 'G16',  floor: 'G', type: 'office',    desc: 'Office suite (270 sf)' },
    { id: 'G17',  floor: 'G', type: 'classroom', desc: 'Classroom (386 sf)' },
    { id: 'G19',  floor: 'G', type: 'classroom', desc: 'Classroom (966 sf)' },
    { id: 'G21',  floor: 'G', type: 'classroom', desc: 'Classroom (968 sf)' },
    { id: 'G23',  floor: 'G', type: 'classroom', desc: 'Large classroom (1,018 sf)' },
    // First floor
    { id: '100',  floor: '1', type: 'classroom', desc: 'Large lecture room (907 sf)' },
    { id: '101',  floor: '1', type: 'classroom', desc: 'Classroom (793 sf)' },
    { id: '107',  floor: '1', type: 'office',    desc: 'Office (117 sf)' },
    { id: '110',  floor: '1', type: 'classroom', desc: 'Classroom (210 sf)' },
    { id: '110A', floor: '1', type: 'classroom', desc: 'Classroom (342 sf)' },
    { id: '113',  floor: '1', type: 'classroom', desc: 'Classroom (520 sf)' },
    { id: '120A', floor: '1', type: 'classroom', desc: 'Classroom (590 sf)' },
    { id: '122',  floor: '1', type: 'office',    desc: 'Office (190 sf)' },
    { id: '137',  floor: '1', type: 'office',    desc: 'Office (154 sf)' },
    { id: '140',  floor: '1', type: 'classroom', desc: 'Classroom (175 sf)' },
    { id: '142',  floor: '1', type: 'classroom', desc: 'Classroom (391 sf)' },
    { id: '144',  floor: '1', type: 'classroom', desc: 'Large classroom (1,050 sf)' },
    { id: '146',  floor: '1', type: 'classroom', desc: 'Classroom (300 sf)' },
    { id: '148',  floor: '1', type: 'classroom', desc: 'Classroom' },
    { id: '151',  floor: '1', type: 'classroom', desc: 'Seminar room (241 sf)' },
    { id: '152',  floor: '1', type: 'classroom', desc: 'Classroom (897 sf)' },
    { id: '153',  floor: '1', type: 'office',    desc: 'Office (120 sf)' },
    // Second floor
    { id: '200',  floor: '2', type: 'classroom', desc: 'Large lecture room (1,453 sf)' },
    { id: '202',  floor: '2', type: 'classroom', desc: 'Classroom (446 sf)' },
    { id: '207',  floor: '2', type: 'office',    desc: 'Office (203 sf)' },
    { id: '209',  floor: '2', type: 'office',    desc: 'Office' },
    { id: '211',  floor: '2', type: 'office',    desc: 'Office (213 sf)' },
    { id: '213',  floor: '2', type: 'office',    desc: 'Office (120 sf)' },
    { id: '215',  floor: '2', type: 'office',    desc: 'Office (118 sf)' },
    { id: '217',  floor: '2', type: 'office',    desc: 'Office (118 sf)' },
    { id: '219',  floor: '2', type: 'office',    desc: 'Office (120 sf)' },
    { id: '221',  floor: '2', type: 'office',    desc: 'Office (119 sf)' },
    { id: '225',  floor: '2', type: 'classroom', desc: 'Classroom (392 sf)' },
    { id: '233',  floor: '2', type: 'office',    desc: 'Office (118 sf)' },
    { id: '234',  floor: '2', type: 'office',    desc: 'Office (208 sf)' },
    { id: '243',  floor: '2', type: 'office',    desc: 'Office (120 sf)' },
    { id: '255',  floor: '2', type: 'office',    desc: 'Office (158 sf)' },
    { id: '270',  floor: '2', type: 'classroom', desc: 'Classroom (162 sf)' },
    // Third floor
    { id: '300',  floor: '3', type: 'classroom', desc: 'Large lecture room (1,244 sf)' },
    { id: '302',  floor: '3', type: 'classroom', desc: 'Classroom (417 sf)' },
    { id: '305',  floor: '3', type: 'office',    desc: 'Office (520 sf)' },
    { id: '307',  floor: '3', type: 'office',    desc: 'Office (119 sf)' },
    { id: '311',  floor: '3', type: 'office',    desc: 'Office (148 sf)' },
    { id: '313',  floor: '3', type: 'office',    desc: 'Office (142 sf)' },
    { id: '321',  floor: '3', type: 'office',    desc: 'Office (120 sf)' },
    { id: '326',  floor: '3', type: 'office',    desc: 'Office (235 sf)' },
    { id: '330',  floor: '3', type: 'office',    desc: 'Office (985 sf)' },
    { id: '346',  floor: '3', type: 'office',    desc: 'Office (360 sf)' },
    { id: '352',  floor: '3', type: 'office',    desc: 'Office (785 sf)' },
    { id: '356',  floor: '3', type: 'classroom', desc: 'Large classroom (1,567 sf)' },
    { id: '365',  floor: '3', type: 'classroom', desc: 'Classroom (533 sf)' },
    { id: '370',  floor: '3', type: 'classroom', desc: 'Classroom (720 sf)' },
  ],

  // ── Academic B (Bldg 070) ───────────────────────────────────────────
  AB: [
    // Ground floor
    { id: 'BG02', floor: 'G', type: 'classroom', desc: 'Large classroom (1,585 sf)' },
    { id: 'BG03', floor: 'G', type: 'classroom', desc: 'Classroom (946 sf)' },
    { id: 'BG05', floor: 'G', type: 'classroom', desc: 'Classroom (416 sf)' },
    { id: 'BG07', floor: 'G', type: 'office',    desc: 'Office (224 sf)' },
    { id: 'BG09', floor: 'G', type: 'office',    desc: 'Office (165 sf)' },
    { id: 'BG11', floor: 'G', type: 'office',    desc: 'Office (182 sf)' },
    { id: 'BG13', floor: 'G', type: 'office',    desc: 'Office (119 sf)' },
    { id: 'BG13A',floor: 'G', type: 'classroom', desc: 'Classroom (500 sf)' },
    { id: 'BG19', floor: 'G', type: 'office',    desc: 'Office' },
    { id: 'BG21', floor: 'G', type: 'office',    desc: 'Office (108 sf)' },
    { id: 'BG25', floor: 'G', type: 'office',    desc: 'Office (124 sf)' },
    { id: 'BG35', floor: 'G', type: 'classroom', desc: 'Large classroom (1,321 sf)' },
    // First floor
    { id: 'B101', floor: '1', type: 'office',    desc: 'Office (151 sf)' },
    { id: 'B103', floor: '1', type: 'office',    desc: 'Office (151 sf)' },
    { id: 'B105', floor: '1', type: 'office',    desc: 'Office (244 sf)' },
    { id: 'B107', floor: '1', type: 'office',    desc: 'Office (146 sf)' },
    { id: 'B109', floor: '1', type: 'office',    desc: 'Office (121 sf)' },
    { id: 'B111', floor: '1', type: 'office',    desc: 'Office (112 sf)' },
    { id: 'B113', floor: '1', type: 'classroom', desc: 'Classroom (547 sf)' },
    { id: 'B114', floor: '1', type: 'classroom', desc: 'Classroom (267 sf)' },
    { id: 'B115', floor: '1', type: 'office',    desc: 'Office (162 sf)' },
    { id: 'B117', floor: '1', type: 'office',    desc: 'Office (161 sf)' },
    { id: 'B124', floor: '1', type: 'classroom', desc: 'Classroom (878 sf)' },
    { id: 'B125', floor: '1', type: 'classroom', desc: 'Classroom (587 sf)' },
    { id: 'B127', floor: '1', type: 'office',    desc: 'Office (137 sf)' },
    { id: 'B130', floor: '1', type: 'classroom', desc: 'Classroom (406 sf)' },
    { id: 'B133', floor: '1', type: 'classroom', desc: 'Classroom (624 sf)' },
    // Second floor
    { id: 'B201', floor: '2', type: 'office',    desc: 'Office (272 sf)' },
    { id: 'B203', floor: '2', type: 'office',    desc: 'Office (181 sf)' },
    { id: 'B205', floor: '2', type: 'office',    desc: 'Office (315 sf)' },
    { id: 'B207', floor: '2', type: 'office',    desc: 'Office' },
    { id: 'B209', floor: '2', type: 'classroom', desc: 'Classroom (476 sf)' },
    { id: 'B211', floor: '2', type: 'office',    desc: 'Office (257 sf)' },
    { id: 'B221', floor: '2', type: 'classroom', desc: 'Classroom (348 sf)' },
    { id: 'B223', floor: '2', type: 'office',    desc: 'Office (162 sf)' },
    { id: 'B225', floor: '2', type: 'office',    desc: 'Office (118 sf)' },
    { id: 'B228', floor: '2', type: 'classroom', desc: 'Classroom (804 sf)' },
    { id: 'B230', floor: '2', type: 'classroom', desc: 'Classroom (433 sf)' },
    { id: 'B234', floor: '2', type: 'classroom', desc: 'Classroom (473 sf)' },
    { id: 'B243', floor: '2', type: 'office',    desc: 'Office (113 sf)' },
    { id: 'B245', floor: '2', type: 'classroom', desc: 'Classroom (247 sf)' },
    // Third floor
    { id: 'B302', floor: '3', type: 'office',    desc: 'Office (139 sf)' },
    { id: 'B305', floor: '3', type: 'office',    desc: 'Office (117 sf)' },
    { id: 'B307', floor: '3', type: 'office',    desc: 'Office (120 sf)' },
    { id: 'B315', floor: '3', type: 'classroom', desc: 'Classroom (275 sf)' },
    { id: 'B317', floor: '3', type: 'office',    desc: 'Office (228 sf)' },
    { id: 'B319', floor: '3', type: 'office',    desc: 'Office (277 sf)' },
    { id: 'B327', floor: '3', type: 'office',    desc: 'Office (142 sf)' },
    { id: 'B329', floor: '3', type: 'office',    desc: 'Office (161 sf)' },
    { id: 'B340', floor: '3', type: 'classroom', desc: 'Large classroom (2,800 sf)' },
    { id: 'B344', floor: '3', type: 'classroom', desc: 'Classroom (280 sf)' },
    { id: 'B346', floor: '3', type: 'classroom', desc: 'Classroom (1,254 sf)' },
  ],

  // ── Engineering Building (Bldg 065) ─────────────────────────────────
  EB: [
    // Basement
    { id: 'A1',   floor: 'B', type: 'classroom', desc: 'Basement classroom' },
    { id: 'A2',   floor: 'B', type: 'lab',       desc: 'Mechatronics lab' },
    { id: 'A3',   floor: 'B', type: 'lab',       desc: 'Controls & robotics lab' },
    { id: 'A4',   floor: 'B', type: 'lab',       desc: 'Machine shop' },
    { id: 'A5',   floor: 'B', type: 'lab',       desc: 'Fabrication & prototyping lab' },
    { id: 'A6',   floor: 'B', type: 'lab',       desc: 'Electronics lab' },
    // Main floor (entry level)
    { id: 'B1',   floor: 'N', type: 'classroom', desc: 'Classroom' },
    { id: 'B3',   floor: 'N', type: 'classroom', desc: 'Classroom' },
    { id: 'B5',   floor: 'N', type: 'classroom', desc: 'Classroom' },
    { id: 'B7',   floor: 'N', type: 'lab',       desc: 'Computer lab' },
    { id: 'B9',   floor: 'N', type: 'lab',       desc: 'Teaching lab' },
    { id: 'C1',   floor: 'N', type: 'classroom', desc: 'Classroom' },
    { id: 'C3',   floor: 'N', type: 'classroom', desc: 'Classroom' },
    { id: 'C5',   floor: 'N', type: 'office',    desc: "Dean's Office — Watson School of Engineering" },
    { id: 'C7',   floor: 'N', type: 'office',    desc: 'Watson School advising office' },
    { id: 'C9',   floor: 'N', type: 'office',    desc: 'Watson School main office' },
    { id: 'D1',   floor: 'N', type: 'auditorium',desc: 'Large lecture hall (auditorium)' },
    { id: 'D3',   floor: 'N', type: 'classroom', desc: 'Mid-size classroom' },
    { id: 'E1',   floor: 'N', type: 'lab',       desc: 'Teaching lab' },
    { id: 'F1',   floor: 'N', type: 'lab',       desc: 'Research lab' },
    // 2nd floor — ECE department
    { id: 'G1',   floor: '2', type: 'lab',       desc: 'Computer Engineering lab' },
    { id: 'G3',   floor: '2', type: 'lab',       desc: 'ECE circuits lab' },
    { id: 'G5',   floor: '2', type: 'lab',       desc: 'Signals & systems lab' },
    { id: 'H1',   floor: '2', type: 'office',    desc: 'ECE department office' },
    { id: 'H3',   floor: '2', type: 'office',    desc: 'ECE faculty office' },
    { id: 'H5',   floor: '2', type: 'office',    desc: 'ECE faculty office' },
    { id: 'H7',   floor: '2', type: 'office',    desc: 'ECE faculty office' },
    { id: 'H9',   floor: '2', type: 'office',    desc: 'ECE faculty office' },
    { id: 'H11',  floor: '2', type: 'office',    desc: 'ECE faculty office' },
    { id: 'H13',  floor: '2', type: 'office',    desc: 'ECE faculty office' },
    { id: 'J1',   floor: '2', type: 'lab',       desc: 'VLSI & embedded systems lab' },
    { id: 'K1',   floor: '2', type: 'office',    desc: 'CS faculty offices' },
    { id: 'K3',   floor: '2', type: 'office',    desc: 'CS faculty office' },
    { id: 'K5',   floor: '2', type: 'office',    desc: 'CS faculty office' },
    { id: 'K7',   floor: '2', type: 'office',    desc: 'CS faculty office' },
    { id: 'L1',   floor: '2', type: 'lab',       desc: 'Software engineering lab' },
    { id: 'M1',   floor: '2', type: 'lab',       desc: 'Research lab' },
    // 3rd floor — ME / ISE / Systems Science
    { id: 'N1',   floor: '3', type: 'lab',       desc: 'Systems Science lab' },
    { id: 'N3',   floor: '3', type: 'lab',       desc: 'Simulation & modeling lab' },
    { id: 'P1',   floor: '3', type: 'office',    desc: 'ME department office' },
    { id: 'P3',   floor: '3', type: 'office',    desc: 'ME faculty office' },
    { id: 'P5',   floor: '3', type: 'office',    desc: 'ME faculty office' },
    { id: 'P7',   floor: '3', type: 'office',    desc: 'ME faculty office' },
    { id: 'P9',   floor: '3', type: 'office',    desc: 'ISE faculty office' },
    { id: 'P11',  floor: '3', type: 'office',    desc: 'ISE faculty office' },
    { id: 'P13',  floor: '3', type: 'office',    desc: 'ISE faculty office' },
    { id: 'Q1',   floor: '3', type: 'lab',       desc: 'Thermal/fluids research lab' },
    { id: 'R1',   floor: '3', type: 'lab',       desc: 'Advanced materials lab' },
    // 4th floor — BME / upper research
    { id: 'S1',   floor: '4', type: 'lab',       desc: 'Biomedical Engineering lab' },
    { id: 'S3',   floor: '4', type: 'lab',       desc: 'BME research lab' },
    { id: 'T1',   floor: '4', type: 'office',    desc: 'BME department office' },
    { id: 'T3',   floor: '4', type: 'office',    desc: 'BME faculty office' },
    { id: 'T5',   floor: '4', type: 'office',    desc: 'BME faculty office' },
    { id: 'T7',   floor: '4', type: 'office',    desc: 'Faculty office' },
    { id: 'T9',   floor: '4', type: 'office',    desc: 'Faculty office' },
  ],

  // ── Lecture Hall (Bldg 034) ─────────────────────────────────────────
  LH: [
    // Basement — lecture halls and offices
    { id: 'G01',  floor: 'G', type: 'classroom', desc: 'Seminar room' },
    { id: 'G02',  floor: 'G', type: 'classroom', desc: 'Classroom (730 sf)' },
    { id: 'G04',  floor: 'G', type: 'classroom', desc: 'Classroom (1,225 sf)' },
    { id: 'G06',  floor: 'G', type: 'classroom', desc: 'Classroom (590 sf)' },
    { id: 'G08',  floor: 'G', type: 'classroom', desc: 'Classroom' },
    { id: 'G10',  floor: 'G', type: 'classroom', desc: 'Classroom (770 sf)' },
    { id: 'G14',  floor: 'G', type: 'classroom', desc: 'Classroom (492 sf)' },
    // First floor — main lecture halls
    { id: '100',  floor: '1', type: 'classroom', desc: 'Classroom (907 sf)' },
    { id: '101',  floor: '1', type: 'classroom', desc: 'Classroom (793 sf)' },
    { id: '110A', floor: '1', type: 'classroom', desc: 'Classroom (342 sf)' },
    { id: '113',  floor: '1', type: 'classroom', desc: 'Lecture room (520 sf)' },
    { id: '144',  floor: '1', type: 'auditorium',desc: 'Large lecture hall (1,050 sf)' },
    { id: '146',  floor: '1', type: 'classroom', desc: 'Classroom (300 sf)' },
    { id: '148',  floor: '1', type: 'classroom', desc: 'Classroom' },
    { id: '152',  floor: '1', type: 'classroom', desc: 'Classroom (897 sf)' },
    // Second floor
    { id: '200',  floor: '2', type: 'classroom', desc: 'Lecture room (1,453 sf)' },
    { id: '202',  floor: '2', type: 'classroom', desc: 'Classroom (446 sf)' },
    { id: '225',  floor: '2', type: 'classroom', desc: 'Classroom (392 sf)' },
    { id: '270',  floor: '2', type: 'classroom', desc: 'Classroom' },
    // Third floor
    { id: '300',  floor: '3', type: 'classroom', desc: 'Lecture room (1,244 sf)' },
    { id: '302',  floor: '3', type: 'classroom', desc: 'Classroom (417 sf)' },
    { id: '356',  floor: '3', type: 'classroom', desc: 'Classroom (1,567 sf)' },
    { id: '365',  floor: '3', type: 'classroom', desc: 'Classroom (533 sf)' },
    { id: '370',  floor: '3', type: 'classroom', desc: 'Classroom (720 sf)' },
  ],

  // ── Science I (Bldg 003) ────────────────────────────────────────────
  S1: [
    // Ground floor
    { id: 'G21',  floor: 'G', type: 'classroom', desc: 'Classroom (816 sf)' },
    { id: 'G24',  floor: 'G', type: 'office',    desc: 'Office (317 sf)' },
    { id: 'G26',  floor: 'G', type: 'lab',       desc: 'Lab (146 sf)' },
    { id: 'G28',  floor: 'G', type: 'lab',       desc: 'Lab (457 sf)' },
    { id: 'G30',  floor: 'G', type: 'lab',       desc: 'Lab (940 sf)' },
    { id: 'G31',  floor: 'G', type: 'lab',       desc: 'Large lab (1,001 sf)' },
    { id: 'G32',  floor: 'G', type: 'lab',       desc: 'Large lab (2,800 sf)' },
    { id: 'G40',  floor: 'G', type: 'lab',       desc: 'Lab (822 sf)' },
    { id: 'G42',  floor: 'G', type: 'lab',       desc: 'Lab (136 sf)' },
    { id: 'G48',  floor: 'G', type: 'lab',       desc: 'Lab (879 sf)' },
    { id: 'G50',  floor: 'G', type: 'classroom', desc: 'Classroom (1,123 sf)' },
    { id: 'G52',  floor: 'G', type: 'lab',       desc: 'Lab (384 sf)' },
    { id: 'G54',  floor: 'G', type: 'lab',       desc: 'Lab (204 sf)' },
    { id: 'G56',  floor: 'G', type: 'lab',       desc: 'Large lab (1,048 sf)' },
    { id: 'G57',  floor: 'G', type: 'lab',       desc: 'Lab (701 sf)' },
    { id: 'G59',  floor: 'G', type: 'lab',       desc: 'Lab (627 sf)' },
    { id: 'G60',  floor: 'G', type: 'lab',       desc: 'Lab (178 sf)' },
    { id: 'G62',  floor: 'G', type: 'lab',       desc: 'Lab (192 sf)' },
    { id: 'G63',  floor: 'G', type: 'lab',       desc: 'Lab (140 sf)' },
    { id: 'G66',  floor: 'G', type: 'lab',       desc: 'Lab (866 sf)' },
    { id: 'G68',  floor: 'G', type: 'lab',       desc: 'Lab (704 sf)' },
    { id: 'G69',  floor: 'G', type: 'lab',       desc: 'Lab (808 sf)' },
    { id: 'G70',  floor: 'G', type: 'lab',       desc: 'Lab (334 sf)' },
    { id: 'G72',  floor: 'G', type: 'lab',       desc: 'Lab (369 sf)' },
    // First floor
    { id: '100',  floor: '1', type: 'classroom', desc: 'Large classroom (1,735 sf)' },
    { id: '102',  floor: '1', type: 'classroom', desc: 'Classroom (260 sf)' },
    { id: '103',  floor: '1', type: 'lab',       desc: 'Lab (516 sf)' },
    { id: '105',  floor: '1', type: 'lab',       desc: 'Lab (271 sf)' },
    { id: '107',  floor: '1', type: 'lab',       desc: 'Lab (515 sf)' },
    { id: '108',  floor: '1', type: 'lab',       desc: 'Lab (243 sf)' },
    { id: '109',  floor: '1', type: 'lab',       desc: 'Lab (338 sf)' },
    { id: '110B', floor: '1', type: 'lab',       desc: 'Lab (243 sf)' },
    { id: '111',  floor: '1', type: 'classroom', desc: 'Classroom (473 sf)' },
    { id: '112',  floor: '1', type: 'classroom', desc: 'Classroom (1,189 sf)' },
    { id: '112A', floor: '1', type: 'classroom', desc: 'Classroom (213 sf)' },
    { id: '114A', floor: '1', type: 'classroom', desc: 'Classroom (244 sf)' },
    { id: '119',  floor: '1', type: 'office',    desc: 'Office (352 sf)' },
    { id: '121',  floor: '1', type: 'lab',       desc: 'Large lab (1,072 sf)' },
    { id: '122',  floor: '1', type: 'lab',       desc: 'Lab (1,294 sf)' },
    { id: '123',  floor: '1', type: 'lab',       desc: 'Lab (752 sf)' },
    { id: '135',  floor: '1', type: 'lab',       desc: 'Lab (245 sf)' },
    { id: '136',  floor: '1', type: 'lab',       desc: 'Lab (605 sf)' },
    { id: '137',  floor: '1', type: 'office',    desc: 'Office (333 sf)' },
    { id: '138',  floor: '1', type: 'lab',       desc: 'Lab (538 sf)' },
    { id: '139B', floor: '1', type: 'office',    desc: 'Office (219 sf)' },
    { id: '141',  floor: '1', type: 'lab',       desc: 'Lab' },
    { id: '142',  floor: '1', type: 'lab',       desc: 'Lab' },
    { id: '144',  floor: '1', type: 'lab',       desc: 'Large lab (1,062 sf)' },
    { id: '145',  floor: '1', type: 'lab',       desc: 'Lab (1,054 sf)' },
    { id: '146',  floor: '1', type: 'lab',       desc: 'Lab (305 sf)' },
    { id: '148',  floor: '1', type: 'lab',       desc: 'Lab (1,864 sf)' },
    { id: '151',  floor: '1', type: 'lab',       desc: 'Lab (154 sf)' },
    { id: '159',  floor: '1', type: 'lab',       desc: 'Lab (340 sf)' },
    { id: '162',  floor: '1', type: 'lab',       desc: 'Large lab (1,026 sf)' },
    { id: '163',  floor: '1', type: 'lab',       desc: 'Lab (870 sf)' },
    { id: '165',  floor: '1', type: 'lab',       desc: 'Lab (448 sf)' },
    { id: '167',  floor: '1', type: 'lab',       desc: 'Lab (491 sf)' },
    { id: '168',  floor: '1', type: 'lab',       desc: 'Lab (538 sf)' },
    { id: '169',  floor: '1', type: 'lab',       desc: 'Lab (711 sf)' },
    { id: '170A', floor: '1', type: 'lab',       desc: 'Lab' },
    { id: '172',  floor: '1', type: 'lab',       desc: 'Lab (146 sf)' },
    // Second floor
    { id: '200',  floor: '2', type: 'classroom', desc: 'Large classroom (1,809 sf)' },
    { id: '201',  floor: '2', type: 'office',    desc: 'Office (113 sf)' },
    { id: '202',  floor: '2', type: 'lab',       desc: 'Lab (108 sf)' },
    { id: '203',  floor: '2', type: 'lab',       desc: 'Lab (210 sf)' },
    { id: '204',  floor: '2', type: 'lab',       desc: 'Lab (214 sf)' },
    { id: '205',  floor: '2', type: 'lab',       desc: 'Lab (329 sf)' },
    { id: '207',  floor: '2', type: 'office',    desc: 'Office (100 sf)' },
    { id: '209',  floor: '2', type: 'office',    desc: 'Office (102 sf)' },
    { id: '213',  floor: '2', type: 'office',    desc: 'Office (126 sf)' },
    { id: '215',  floor: '2', type: 'lab',       desc: 'Lab (250 sf)' },
    { id: '216',  floor: '2', type: 'lab',       desc: 'Lab (218 sf)' },
    { id: '218',  floor: '2', type: 'lab',       desc: 'Lab (262 sf)' },
    { id: '220',  floor: '2', type: 'lab',       desc: 'Lab (262 sf)' },
    { id: '222',  floor: '2', type: 'lab',       desc: 'Lab (196 sf)' },
    { id: '225',  floor: '2', type: 'classroom', desc: 'Classroom (495 sf)' },
    { id: '228',  floor: '2', type: 'lab',       desc: 'Lab (803 sf)' },
    { id: '230',  floor: '2', type: 'lab',       desc: 'Lab (678 sf)' },
    { id: '242',  floor: '2', type: 'lab',       desc: 'Lab (253 sf)' },
    { id: '252',  floor: '2', type: 'lab',       desc: 'Lab (103 sf)' },
    { id: '254',  floor: '2', type: 'lab',       desc: 'Lab (941 sf)' },
    { id: '256',  floor: '2', type: 'lab',       desc: 'Lab (145 sf)' },
    { id: '262',  floor: '2', type: 'lab',       desc: 'Lab (848 sf)' },
    { id: '263',  floor: '2', type: 'lab',       desc: 'Lab (862 sf)' },
    { id: '265',  floor: '2', type: 'lab',       desc: 'Lab (323 sf)' },
    { id: '267',  floor: '2', type: 'lab',       desc: 'Lab (968 sf)' },
    { id: '271',  floor: '2', type: 'lab',       desc: 'Lab (140 sf)' },
  ],

  // ── Science II (Bldg 033) ───────────────────────────────────────────
  S2: [
    // Basement
    { id: 'B1',   floor: 'B', type: 'lab',       desc: 'Lab (881 sf)' },
    { id: 'B1A',  floor: 'B', type: 'lab',       desc: 'Large lab (1,172 sf)' },
    { id: 'B2',   floor: 'B', type: 'lab',       desc: 'Lab (1,306 sf)' },
    { id: 'B3',   floor: 'B', type: 'lab',       desc: 'Lab (847 sf)' },
    { id: 'B5',   floor: 'B', type: 'lab',       desc: 'Lab (221 sf)' },
    { id: 'B6',   floor: 'B', type: 'lab',       desc: 'Lab (419 sf)' },
    { id: 'B7',   floor: 'B', type: 'lab',       desc: 'Lab (274 sf)' },
    { id: 'B11',  floor: 'B', type: 'lab',       desc: 'Lab (759 sf)' },
    { id: 'B14',  floor: 'B', type: 'lab',       desc: 'Lab (449 sf)' },
    { id: 'B15',  floor: 'B', type: 'lab',       desc: 'Large lab (1,024 sf)' },
    { id: 'B23',  floor: 'B', type: 'lab',       desc: 'Lab (225 sf)' },
    { id: 'B24',  floor: 'B', type: 'lab',       desc: 'Lab (446 sf)' },
    { id: 'B25',  floor: 'B', type: 'lab',       desc: 'Lab (672 sf)' },
    { id: 'B30',  floor: 'B', type: 'lab',       desc: 'Lab (412 sf)' },
    { id: 'B32',  floor: 'B', type: 'lab',       desc: 'Lab (282 sf)' },
    { id: 'B33',  floor: 'B', type: 'lab',       desc: 'Large lab (2,461 sf)' },
    // Ground floor
    { id: 'G1',   floor: 'G', type: 'lab',       desc: 'Lab (767 sf)' },
    { id: 'G2',   floor: 'G', type: 'lab',       desc: 'Lab (353 sf)' },
    { id: 'G3',   floor: 'G', type: 'lab',       desc: 'Lab (733 sf)' },
    { id: 'G4',   floor: 'G', type: 'lab',       desc: 'Lab (740 sf)' },
    { id: 'G5',   floor: 'G', type: 'lab',       desc: 'Lab (424 sf)' },
    { id: 'G7',   floor: 'G', type: 'lab',       desc: 'Lab (738 sf)' },
    { id: 'G8',   floor: 'G', type: 'lab',       desc: 'Lab (754 sf)' },
    { id: 'G9',   floor: 'G', type: 'lab',       desc: 'Lab (592 sf)' },
    { id: 'G10',  floor: 'G', type: 'lab',       desc: 'Lab' },
    { id: 'G11',  floor: 'G', type: 'lab',       desc: 'Lab (759 sf)' },
    { id: 'G14',  floor: 'G', type: 'lab',       desc: 'Lab (857 sf)' },
    { id: 'G19',  floor: 'G', type: 'lab',       desc: 'Lab (562 sf)' },
    { id: 'G20',  floor: 'G', type: 'lab',       desc: 'Lab (444 sf)' },
    { id: 'G22',  floor: 'G', type: 'lab',       desc: 'Lab (209 sf)' },
    { id: 'G24',  floor: 'G', type: 'lab',       desc: 'Lab (633 sf)' },
    { id: 'G25',  floor: 'G', type: 'lab',       desc: 'Lab (331 sf)' },
    { id: 'G29',  floor: 'G', type: 'classroom', desc: 'Classroom (614 sf)' },
    { id: 'G31',  floor: 'G', type: 'lab',       desc: 'Lab (618 sf)' },
    { id: 'G32',  floor: 'G', type: 'classroom', desc: 'Classroom (2,081 sf)' },
    { id: 'G33',  floor: 'G', type: 'lab',       desc: 'Lab (188 sf)' },
    { id: 'G38',  floor: 'G', type: 'lab',       desc: 'Lab (352 sf)' },
    { id: 'G39',  floor: 'G', type: 'lab',       desc: 'Lab (396 sf)' },
    { id: 'G40',  floor: 'G', type: 'lab',       desc: 'Lab (221 sf)' },
    { id: 'G43',  floor: 'G', type: 'lab',       desc: 'Large lab (1,495 sf)' },
    { id: 'G44',  floor: 'G', type: 'lab',       desc: 'Large lab (1,084 sf)' },
    { id: 'G50',  floor: 'G', type: 'lab',       desc: 'Large lab (1,098 sf)' },
    { id: 'G52',  floor: 'G', type: 'lab',       desc: 'Large lab (1,110 sf)' },
    { id: 'G55',  floor: 'G', type: 'lab',       desc: 'Lab (753 sf)' },
    { id: 'G56',  floor: 'G', type: 'lab',       desc: 'Lab (972 sf)' },
    { id: 'G70',  floor: 'G', type: 'lab',       desc: 'Lab (155 sf)' },
    { id: 'G71',  floor: 'G', type: 'lab',       desc: 'Lab (350 sf)' },
    { id: 'G72',  floor: 'G', type: 'lab',       desc: 'Lab (91 sf)' },
    { id: 'G74',  floor: 'G', type: 'lab',       desc: 'Lab (476 sf)' },
    // First floor
    { id: '100',  floor: '1', type: 'classroom', desc: 'Physics lecture room (1,735 sf)' },
    { id: '102',  floor: '1', type: 'lab',       desc: 'Physics lab (1,733 sf)' },
    { id: '104',  floor: '1', type: 'lab',       desc: 'Lab (448 sf)' },
    { id: '106',  floor: '1', type: 'lab',       desc: 'Lab (1,115 sf)' },
    { id: '107',  floor: '1', type: 'lab',       desc: 'Lab (1,115 sf)' },
    { id: '108',  floor: '1', type: 'lab',       desc: 'Lab (439 sf)' },
    { id: '110',  floor: '1', type: 'lab',       desc: 'Lab (1,082 sf)' },
    { id: '111',  floor: '1', type: 'lab',       desc: 'Lab (1,081 sf)' },
    { id: '112',  floor: '1', type: 'lab',       desc: 'Lab (103 sf)' },
    { id: '116',  floor: '1', type: 'lab',       desc: 'Lab (223 sf)' },
    { id: '117',  floor: '1', type: 'lab',       desc: 'Lab (213 sf)' },
    { id: '120',  floor: '1', type: 'lab',       desc: 'Lab (216 sf)' },
    { id: '122',  floor: '1', type: 'lab',       desc: 'Lab (213 sf)' },
    { id: '123',  floor: '1', type: 'lab',       desc: 'Lab (199 sf)' },
    { id: '125',  floor: '1', type: 'lab',       desc: 'Lab (156 sf)' },
    { id: '126',  floor: '1', type: 'lab',       desc: 'Lab (507 sf)' },
    { id: '127',  floor: '1', type: 'lab',       desc: 'Lab (345 sf)' },
    { id: '128',  floor: '1', type: 'lab',       desc: 'Lab (210 sf)' },
    { id: '129',  floor: '1', type: 'lab',       desc: 'Lab (223 sf)' },
    { id: '131',  floor: '1', type: 'lab',       desc: 'Large lab (1,128 sf)' },
    { id: '132',  floor: '1', type: 'lab',       desc: 'Lab (430 sf)' },
    { id: '133',  floor: '1', type: 'lab',       desc: 'Lab (179 sf)' },
    { id: '134',  floor: '1', type: 'lab',       desc: 'Lab (662 sf)' },
    { id: '135',  floor: '1', type: 'lab',       desc: 'Lab (662 sf)' },
    { id: '137',  floor: '1', type: 'lab',       desc: 'Lab (205 sf)' },
    { id: '138',  floor: '1', type: 'lab',       desc: 'Lab (479 sf)' },
    { id: '139',  floor: '1', type: 'lab',       desc: 'Large lab (1,734 sf)' },
    { id: '140',  floor: '1', type: 'lab',       desc: 'Large lab (1,101 sf)' },
    { id: '141',  floor: '1', type: 'lab',       desc: 'Lab (764 sf)' },
    { id: '142',  floor: '1', type: 'lab',       desc: 'Lab (758 sf)' },
    { id: '143',  floor: '1', type: 'lab',       desc: 'Large lab (1,078 sf)' },
    { id: '144',  floor: '1', type: 'lab',       desc: 'Large lab (1,097 sf)' },
    { id: '145',  floor: '1', type: 'lab',       desc: 'Large lab (1,117 sf)' },
    { id: '148',  floor: '1', type: 'lab',       desc: 'Lab' },
    { id: '150',  floor: '1', type: 'lab',       desc: 'Lab (92 sf)' },
    { id: '152',  floor: '1', type: 'lab',       desc: 'Lab (218 sf)' },
    { id: '155',  floor: '1', type: 'lab',       desc: 'Lab (210 sf)' },
    { id: '156',  floor: '1', type: 'lab',       desc: 'Lab (212 sf)' },
    { id: '157',  floor: '1', type: 'lab',       desc: 'Lab (194 sf)' },
    { id: '158',  floor: '1', type: 'lab',       desc: 'Lab (316 sf)' },
    { id: '159',  floor: '1', type: 'lab',       desc: 'Lab (388 sf)' },
    // Second floor
    { id: '200',  floor: '2', type: 'classroom', desc: 'Large classroom (1,809 sf)' },
    { id: '201',  floor: '2', type: 'lab',       desc: 'Large lab (1,741 sf)' },
    { id: '202',  floor: '2', type: 'lab',       desc: 'Lab (108 sf)' },
    { id: '205',  floor: '2', type: 'lab',       desc: 'Lab (207 sf)' },
    { id: '206',  floor: '2', type: 'lab',       desc: 'Lab (1,119 sf)' },
    { id: '207',  floor: '2', type: 'lab',       desc: 'Lab (1,118 sf)' },
    { id: '208',  floor: '2', type: 'lab',       desc: 'Lab (395 sf)' },
    { id: '210',  floor: '2', type: 'lab',       desc: 'Lab (1,126 sf)' },
    { id: '213',  floor: '2', type: 'lab',       desc: 'Lab (1,086 sf)' },
    { id: '219',  floor: '2', type: 'lab',       desc: 'Lab (101 sf)' },
    { id: '220',  floor: '2', type: 'lab',       desc: 'Lab (213 sf)' },
    { id: '221',  floor: '2', type: 'lab',       desc: 'Lab (215 sf)' },
    { id: '222',  floor: '2', type: 'lab',       desc: 'Lab (213 sf)' },
    { id: '223',  floor: '2', type: 'lab',       desc: 'Lab (213 sf)' },
    { id: '225',  floor: '2', type: 'lab',       desc: 'Lab (293 sf)' },
    { id: '231',  floor: '2', type: 'lab',       desc: 'Lab (824 sf)' },
    { id: '236',  floor: '2', type: 'lab',       desc: 'Lab (222 sf)' },
    { id: '238',  floor: '2', type: 'lab',       desc: 'Lab (137 sf)' },
    { id: '241',  floor: '2', type: 'lab',       desc: 'Lab (210 sf)' },
    { id: '242',  floor: '2', type: 'lab',       desc: 'Lab (523 sf)' },
    { id: '243',  floor: '2', type: 'lab',       desc: 'Lab (507 sf)' },
    { id: '244',  floor: '2', type: 'lab',       desc: 'Lab (253 sf)' },
    { id: '246',  floor: '2', type: 'lab',       desc: 'Large lab (1,977 sf)' },
    { id: '247',  floor: '2', type: 'lab',       desc: 'Large lab (1,154 sf)' },
    { id: '248',  floor: '2', type: 'lab',       desc: 'Large lab (1,153 sf)' },
    { id: '249',  floor: '2', type: 'lab',       desc: 'Large lab (1,522 sf)' },
    { id: '250',  floor: '2', type: 'lab',       desc: 'Large lab (1,151 sf)' },
    // Third floor
    { id: '301',  floor: '3', type: 'lab',       desc: 'Large lab (1,619 sf)' },
    { id: '302',  floor: '3', type: 'lab',       desc: 'Large lab (1,117 sf)' },
    { id: '303',  floor: '3', type: 'lab',       desc: 'Lab (220 sf)' },
    { id: '305',  floor: '3', type: 'lab',       desc: 'Lab (220 sf)' },
    { id: '306',  floor: '3', type: 'lab',       desc: 'Large lab (1,126 sf)' },
    { id: '307',  floor: '3', type: 'lab',       desc: 'Large lab (1,118 sf)' },
    { id: '308',  floor: '3', type: 'lab',       desc: 'Lab (1,126 sf)' },
    { id: '310',  floor: '3', type: 'office',    desc: 'Office (214 sf)' },
    { id: '311',  floor: '3', type: 'office',    desc: 'Office (138 sf)' },
    { id: '312',  floor: '3', type: 'office',    desc: 'Office (138 sf)' },
    { id: '313',  floor: '3', type: 'lab',       desc: 'Large lab (1,123 sf)' },
    { id: '314',  floor: '3', type: 'lab',       desc: 'Large lab (1,092 sf)' },
    { id: '320',  floor: '3', type: 'office',    desc: 'Office (271 sf)' },
    { id: '321',  floor: '3', type: 'office',    desc: 'Office (158 sf)' },
    { id: '326',  floor: '3', type: 'office',    desc: 'Office (155 sf)' },
    { id: '327',  floor: '3', type: 'lab',       desc: 'Lab (560 sf)' },
    { id: '330',  floor: '3', type: 'lab',       desc: 'Lab (591 sf)' },
    { id: '332',  floor: '3', type: 'lab',       desc: 'Lab (205 sf)' },
    { id: '337',  floor: '3', type: 'lab',       desc: 'Lab (654 sf)' },
    { id: '338',  floor: '3', type: 'lab',       desc: 'Lab (377 sf)' },
    { id: '340',  floor: '3', type: 'lab',       desc: 'Lab (282 sf)' },
    { id: '341',  floor: '3', type: 'lab',       desc: 'Lab (506 sf)' },
    { id: '344',  floor: '3', type: 'lab',       desc: 'Lab (438 sf)' },
    { id: '345',  floor: '3', type: 'lab',       desc: 'Lab (254 sf)' },
  ],

  // ── Science III (Bldg 039) ──────────────────────────────────────────
  S3: [
    // Basement
    { id: 'B45',  floor: 'B', type: 'lab',       desc: 'Large lab (5,350 sf)' },
    { id: 'B49',  floor: 'B', type: 'lab',       desc: 'Lab (215 sf)' },
    { id: 'B50',  floor: 'B', type: 'lab',       desc: 'Lab (264 sf)' },
    { id: 'B55',  floor: 'B', type: 'lab',       desc: 'Lab (357 sf)' },
    { id: 'B56',  floor: 'B', type: 'lab',       desc: 'Lab (876 sf)' },
    { id: 'B64',  floor: 'B', type: 'lab',       desc: 'Lab (286 sf)' },
    { id: 'B72F', floor: 'B', type: 'lab',       desc: 'Lab (470 sf)' },
    { id: 'B74',  floor: 'B', type: 'lab',       desc: 'Lab (114 sf)' },
    { id: 'B78',  floor: 'B', type: 'lab',       desc: 'Lab (205 sf)' },
    { id: 'B81',  floor: 'B', type: 'lab',       desc: 'Lab (90 sf)' },
    { id: 'B83',  floor: 'B', type: 'lab',       desc: 'Lab (301 sf)' },
    { id: 'B93',  floor: 'B', type: 'lab',       desc: 'Lab (201 sf)' },
    { id: 'B99',  floor: 'B', type: 'lab',       desc: 'Lab (204 sf)' },
    // Ground floor
    { id: 'G01',  floor: 'G', type: 'classroom', desc: 'Classroom (205 sf)' },
    { id: 'G03',  floor: 'G', type: 'office',    desc: 'Office (268 sf)' },
    { id: 'G06',  floor: 'G', type: 'lab',       desc: 'Lab (214 sf)' },
    { id: 'G11',  floor: 'G', type: 'office',    desc: 'Office (212 sf)' },
    { id: 'G13',  floor: 'G', type: 'classroom', desc: 'Classroom (524 sf)' },
    { id: 'G17',  floor: 'G', type: 'lab',       desc: 'Lab (667 sf)' },
    { id: 'G21',  floor: 'G', type: 'lab',       desc: 'Lab (835 sf)' },
    { id: 'G25',  floor: 'G', type: 'lab',       desc: 'Lab (866 sf)' },
    { id: 'G29',  floor: 'G', type: 'lab',       desc: 'Lab (670 sf)' },
    { id: 'G33',  floor: 'G', type: 'lab',       desc: 'Lab (555 sf)' },
    { id: 'G37',  floor: 'G', type: 'lab',       desc: 'Lab (430 sf)' },
    { id: 'G41',  floor: 'G', type: 'lab',       desc: 'Lab (210 sf)' },
    { id: 'G45',  floor: 'G', type: 'lab',       desc: 'Lab (256 sf)' },
    { id: 'G47',  floor: 'G', type: 'lab',       desc: 'Lab (428 sf)' },
    { id: 'G49',  floor: 'G', type: 'lab',       desc: 'Lab (212 sf)' },
    { id: 'G51',  floor: 'G', type: 'lab',       desc: 'Lab (115 sf)' },
    { id: 'G54',  floor: 'G', type: 'lab',       desc: 'Lab (432 sf)' },
    { id: 'G56',  floor: 'G', type: 'lab',       desc: 'Lab (170 sf)' },
    { id: 'G58',  floor: 'G', type: 'lab',       desc: 'Lab (210 sf)' },
    { id: 'G92B', floor: 'G', type: 'lab',       desc: 'Lab (421 sf)' },
    { id: 'G94A', floor: 'G', type: 'lab',       desc: 'Lab (430 sf)' },
    { id: 'G96',  floor: 'G', type: 'lab',       desc: 'Lab (855 sf)' },
    { id: 'G98',  floor: 'G', type: 'lab',       desc: 'Loading dock (585 sf)' },
    // First floor
    { id: '100',  floor: '1', type: 'classroom', desc: 'Large classroom (526 sf)' },
    { id: '101',  floor: '1', type: 'lab',       desc: 'Lab (213 sf)' },
    { id: '103',  floor: '1', type: 'lab',       desc: 'Lab (213 sf)' },
    { id: '105',  floor: '1', type: 'lab',       desc: 'Lab (212 sf)' },
    { id: '107',  floor: '1', type: 'lab',       desc: 'Lab (211 sf)' },
    { id: '109',  floor: '1', type: 'lab',       desc: 'Lab (212 sf)' },
    { id: '111',  floor: '1', type: 'lab',       desc: 'Lab (213 sf)' },
    { id: '113',  floor: '1', type: 'lab',       desc: 'Lab (504 sf)' },
    { id: '115',  floor: '1', type: 'lab',       desc: 'Lab (211 sf)' },
    { id: '117',  floor: '1', type: 'lab',       desc: 'Lab (212 sf)' },
    { id: '121A', floor: '1', type: 'lab',       desc: 'Lab (429 sf)' },
    { id: '125',  floor: '1', type: 'lab',       desc: 'Lab (868 sf)' },
    { id: '129',  floor: '1', type: 'lab',       desc: 'Lab (212 sf)' },
    { id: '131',  floor: '1', type: 'lab',       desc: 'Lab (433 sf)' },
    { id: '133A', floor: '1', type: 'lab',       desc: 'Lab (158 sf)' },
    { id: '135',  floor: '1', type: 'lab',       desc: 'Lab (212 sf)' },
    { id: '137A', floor: '1', type: 'lab',       desc: 'Lab (110 sf)' },
    { id: '139',  floor: '1', type: 'lab',       desc: 'Lab (212 sf)' },
    { id: '141',  floor: '1', type: 'lab',       desc: 'Lab (212 sf)' },
    { id: '143',  floor: '1', type: 'lab',       desc: 'Lab (212 sf)' },
    { id: '148',  floor: '1', type: 'lab',       desc: 'Lab (150 sf)' },
    { id: '150',  floor: '1', type: 'lab',       desc: 'Lab (151 sf)' },
    { id: '154',  floor: '1', type: 'lab',       desc: 'Lab (119 sf)' },
    { id: '154B', floor: '1', type: 'lab',       desc: 'Lab (507 sf)' },
    { id: '158B', floor: '1', type: 'lab',       desc: 'Lab (350 sf)' },
    { id: '160',  floor: '1', type: 'lab',       desc: 'Lab (908 sf)' },
    { id: '172',  floor: '1', type: 'lab',       desc: 'Lab (247 sf)' },
    { id: '184',  floor: '1', type: 'lab',       desc: 'Lab (736 sf)' },
    { id: '195B', floor: '1', type: 'lab',       desc: 'Research Greenhouse (1,705 sf)' },
    { id: '195E', floor: '1', type: 'lab',       desc: 'Greenhouse (2,845 sf)' },
    { id: '195G', floor: '1', type: 'lab',       desc: 'Greenhouse (772 sf)' },
    // Second floor
    { id: '200',  floor: '2', type: 'classroom', desc: 'Large classroom (529 sf)' },
    { id: '203',  floor: '2', type: 'lab',       desc: 'Lab (431 sf)' },
    { id: '205',  floor: '2', type: 'lab',       desc: 'Lab (214 sf)' },
    { id: '207',  floor: '2', type: 'lab',       desc: 'Lab (212 sf)' },
    { id: '209',  floor: '2', type: 'lab',       desc: 'Lab (436 sf)' },
    { id: '214',  floor: '2', type: 'lab',       desc: 'Lab (626 sf)' },
    { id: '215',  floor: '2', type: 'lab',       desc: 'Lab (516 sf)' },
    { id: '217',  floor: '2', type: 'lab',       desc: 'Large lab (1,212 sf)' },
    { id: '220',  floor: '2', type: 'lab',       desc: 'Lab (152 sf)' },
    { id: '222',  floor: '2', type: 'lab',       desc: 'Lab (150 sf)' },
    { id: '224',  floor: '2', type: 'lab',       desc: 'Lab (152 sf)' },
    { id: '225A', floor: '2', type: 'lab',       desc: 'Lab (212 sf)' },
    { id: '227',  floor: '2', type: 'lab',       desc: 'Large lab (1,302 sf)' },
    { id: '230',  floor: '2', type: 'lab',       desc: 'Lab (150 sf)' },
    { id: '232',  floor: '2', type: 'lab',       desc: 'Lab (150 sf)' },
    { id: '234',  floor: '2', type: 'lab',       desc: 'Lab (152 sf)' },
    { id: '235',  floor: '2', type: 'lab',       desc: 'Large lab (1,302 sf)' },
    { id: '246A', floor: '2', type: 'lab',       desc: 'Lab (163 sf)' },
    { id: '247A', floor: '2', type: 'office',    desc: 'Office (168 sf)' },
    { id: '248',  floor: '2', type: 'lab',       desc: 'Lab (296 sf)' },
    { id: '250',  floor: '2', type: 'lab',       desc: 'Lab (336 sf)' },
    { id: '258',  floor: '2', type: 'lab',       desc: 'Lab (961 sf)' },
    { id: '260',  floor: '2', type: 'lab',       desc: 'Lab (308 sf)' },
    { id: '265',  floor: '2', type: 'lab',       desc: 'Lab (150 sf)' },
    { id: '268A', floor: '2', type: 'lab',       desc: 'Lab (210 sf)' },
    { id: '270',  floor: '2', type: 'lab',       desc: 'Lab (432 sf)' },
    { id: '270A', floor: '2', type: 'lab',       desc: 'Lab (428 sf)' },
    { id: '280',  floor: '2', type: 'lab',       desc: 'Lab (693 sf)' },
    { id: '282',  floor: '2', type: 'lab',       desc: 'Lab (432 sf)' },
    { id: '282A', floor: '2', type: 'lab',       desc: 'Lab (426 sf)' },
    { id: '285',  floor: '2', type: 'lab',       desc: 'Lab (309 sf)' },
    { id: '293',  floor: '2', type: 'lab',       desc: 'Lab (151 sf)' },
    { id: '295',  floor: '2', type: 'lab',       desc: 'Lab (798 sf)' },
    // Third floor
    { id: '300',  floor: '3', type: 'lab',       desc: 'Lab (611 sf)' },
    { id: '301',  floor: '3', type: 'lab',       desc: 'Large lab (1,840 sf)' },
    { id: '303',  floor: '3', type: 'lab',       desc: 'Large lab (1,103 sf)' },
    { id: '305',  floor: '3', type: 'lab',       desc: 'Lab (628 sf)' },
    { id: '350',  floor: '3', type: 'lab',       desc: 'Lab (248 sf)' },
    { id: '352',  floor: '3', type: 'lab',       desc: 'Lab (261 sf)' },
    { id: '354',  floor: '3', type: 'lab',       desc: 'Lab (261 sf)' },
    { id: '356',  floor: '3', type: 'lab',       desc: 'Lab (262 sf)' },
    { id: '358',  floor: '3', type: 'lab',       desc: 'Lab (805 sf)' },
    { id: '360',  floor: '3', type: 'lab',       desc: 'Lab (261 sf)' },
    { id: '362',  floor: '3', type: 'lab',       desc: 'Lab (262 sf)' },
    { id: '364',  floor: '3', type: 'lab',       desc: 'Lab (261 sf)' },
    { id: '366',  floor: '3', type: 'lab',       desc: 'Lab (245 sf)' },
    { id: '368',  floor: '3', type: 'lab',       desc: 'Lab (759 sf)' },
    { id: '370',  floor: '3', type: 'lab',       desc: 'Lab (298 sf)' },
    { id: '376',  floor: '3', type: 'lab',       desc: 'Lab (262 sf)' },
    { id: '378',  floor: '3', type: 'lab',       desc: 'Lab (262 sf)' },
    { id: '380',  floor: '3', type: 'lab',       desc: 'Lab (261 sf)' },
    { id: '382',  floor: '3', type: 'lab',       desc: 'Lab (262 sf)' },
    { id: '384',  floor: '3', type: 'lab',       desc: 'Lab (534 sf)' },
    { id: '388',  floor: '3', type: 'lab',       desc: 'Lab (260 sf)' },
    { id: '390',  floor: '3', type: 'lab',       desc: 'Lab (262 sf)' },
    { id: '392',  floor: '3', type: 'lab',       desc: 'Lab (263 sf)' },
    { id: '394',  floor: '3', type: 'lab',       desc: 'Lab (263 sf)' },
    { id: '396',  floor: '3', type: 'lab',       desc: 'Lab (262 sf)' },
    { id: '398',  floor: '3', type: 'lab',       desc: 'Lab (264 sf)' },
  ],

  // ── Fine Arts (Bldg 052) ────────────────────────────────────────────
  FA: [
    // Basement
    { id: 'B01',  floor: 'B', type: 'theater',   desc: 'Watters Theater (main stage)' },
    { id: 'B02',  floor: 'B', type: 'theater',   desc: 'Osterhout Concert Theater' },
    { id: 'B03',  floor: 'B', type: 'studio',    desc: 'Music rehearsal room' },
    // Ground floor
    { id: 'G01',  floor: 'G', type: 'studio',    desc: 'Sculpture studio' },
    { id: 'G02',  floor: 'G', type: 'studio',    desc: 'Design studio' },
    { id: 'G03',  floor: 'G', type: 'studio',    desc: 'Choral rehearsal room' },
    { id: 'G04',  floor: 'G', type: 'studio',    desc: 'General rehearsal room' },
    { id: 'G05',  floor: 'G', type: 'studio',    desc: 'Equipment room' },
    // First floor
    { id: '100',  floor: '1', type: 'theater',   desc: 'Studio Theater A (1,252 sf)' },
    { id: '101',  floor: '1', type: 'theater',   desc: 'Studio Theater B' },
    { id: '102',  floor: '1', type: 'studio',    desc: 'Theater scene shop' },
    { id: '103',  floor: '1', type: 'theater',   desc: 'Watters Theater (main stage, 26,798 sf)' },
    { id: '104',  floor: '1', type: 'studio',    desc: 'Costume shop' },
    { id: '105',  floor: '1', type: 'studio',    desc: 'Sculpture studio (3,099 sf)' },
    { id: '106',  floor: '1', type: 'studio',    desc: 'Foundry / metal shop' },
    { id: '107',  floor: '1', type: 'studio',    desc: 'Printmaking studio' },
    { id: '108',  floor: '1', type: 'studio',    desc: 'Painting studio' },
    { id: '109',  floor: '1', type: 'studio',    desc: 'Studio art space' },
    { id: '110',  floor: '1', type: 'studio',    desc: 'Gallery / exhibition space' },
    { id: '111',  floor: '1', type: 'studio',    desc: 'Ceramics studio' },
    // Second floor
    { id: '200',  floor: '2', type: 'studio',    desc: 'Catwalk / technical area' },
    { id: '201',  floor: '2', type: 'studio',    desc: 'Studio art room' },
    { id: '202',  floor: '2', type: 'studio',    desc: 'Drawing studio' },
    { id: '203',  floor: '2', type: 'studio',    desc: 'Photography lab' },
    { id: '204',  floor: '2', type: 'classroom', desc: 'Art history classroom' },
    { id: '205',  floor: '2', type: 'office',    desc: 'Art faculty offices' },
    { id: '206',  floor: '2', type: 'office',    desc: 'Music faculty offices' },
    { id: '207',  floor: '2', type: 'studio',    desc: 'Balcony / performance area' },
    { id: '208',  floor: '2', type: 'studio',    desc: 'Graphic design studio' },
    { id: '209',  floor: '2', type: 'studio',    desc: 'Digital arts lab' },
    { id: '210',  floor: '2', type: 'studio',    desc: 'Gallery / exhibition space' },
  ],

  // ── University Union (Bldg 048) ─────────────────────────────────────
  UU: [
    // Basement
    { id: '002',  floor: 'B', type: 'dining',    desc: 'Munches (food court)' },
    { id: '026',  floor: 'B', type: 'lounge',    desc: 'Billiards room' },
    { id: '028',  floor: 'B', type: 'lounge',    desc: 'Ping pong room' },
    { id: '034',  floor: 'B', type: 'lounge',    desc: 'Coffee House' },
    { id: 'C06A', floor: 'B', type: 'service',   desc: 'Post Office' },
    { id: 'C08',  floor: 'B', type: 'service',   desc: 'Bike Shop' },
    // First floor
    { id: '101',  floor: '1', type: 'room',      desc: 'Multi-purpose room' },
    { id: '104',  floor: '1', type: 'lounge',    desc: 'Tillman Lobby' },
    { id: '108',  floor: '1', type: 'room',      desc: 'Multi-purpose room' },
    { id: '113B', floor: '1', type: 'service',   desc: 'Information desk' },
    { id: '114',  floor: '1', type: 'room',      desc: 'Old Union Hall' },
    { id: '115',  floor: '1', type: 'room',      desc: 'Mandela Room' },
    // Second floor
    { id: '200',  floor: '2', type: 'room',      desc: 'Multi-purpose room' },
    { id: '201',  floor: '2', type: 'room',      desc: 'Multi-purpose room' },
    { id: '202',  floor: '2', type: 'studio',    desc: 'BingTV / WHRW radio studio' },
    { id: '203',  floor: '2', type: 'room',      desc: 'Multi-purpose room' },
    { id: '205',  floor: '2', type: 'room',      desc: 'Multi-purpose room' },
    { id: '206',  floor: '2', type: 'room',      desc: 'Multi-purpose room' },
    { id: '207',  floor: '2', type: 'room',      desc: 'Multi-purpose room' },
    { id: '210',  floor: '2', type: 'room',      desc: 'Multi-purpose room' },
    { id: '213',  floor: '2', type: 'room',      desc: 'Multi-purpose room' },
    { id: '250',  floor: '2', type: 'office',    desc: 'Student org offices' },
    { id: '260',  floor: '2', type: 'office',    desc: 'Student Association offices' },
    { id: '270',  floor: '2', type: 'office',    desc: 'Dean of Students' },
    { id: '276',  floor: '2', type: 'office',    desc: 'Multicultural Resource Center' },
  ],

  // ── Bartle Library (Bldg 002) ───────────────────────────────────────
  LS: [
    { id: 'G01',  floor: 'G', type: 'stacks',    desc: 'Ground floor stacks' },
    { id: 'G02',  floor: 'G', type: 'service',   desc: 'Government documents' },
    { id: '101',  floor: '1', type: 'service',   desc: 'Circulation & Reserve desk' },
    { id: '102',  floor: '1', type: 'lab',       desc: 'Research & Information Services' },
    { id: '103',  floor: '1', type: 'room',      desc: 'Study room' },
    { id: '104',  floor: '1', type: 'room',      desc: 'Reading room' },
    { id: '201',  floor: '2', type: 'stacks',    desc: 'General stacks — A–P call numbers' },
    { id: '202',  floor: '2', type: 'room',      desc: 'Study room' },
    { id: '301',  floor: '3', type: 'stacks',    desc: 'General stacks — P–Z call numbers' },
    { id: '302',  floor: '3', type: 'room',      desc: 'Study room' },
  ],

  // ── Library Tower (Bldg 036) ────────────────────────────────────────
  LN: [
    { id: '101',  floor: '1', type: 'stacks',    desc: 'Stacks / reading area' },
    { id: '201',  floor: '2', type: 'stacks',    desc: 'Stacks / reading area' },
    { id: '301',  floor: '3', type: 'stacks',    desc: 'Stacks / reading area' },
    { id: '401',  floor: '4', type: 'room',      desc: 'Reading room with campus views' },
    { id: '501',  floor: '5', type: 'room',      desc: 'Seminar / study room' },
    { id: '601',  floor: '6', type: 'room',      desc: 'Upper reading room' },
    { id: '701',  floor: '7', type: 'room',      desc: 'Research collection' },
    { id: '801',  floor: '8', type: 'room',      desc: 'Archival collection' },
    { id: '901',  floor: '9', type: 'room',      desc: 'Top-floor reading room — panoramic views' },
  ],

  // ── Events Center (Bldg 135) ────────────────────────────────────────
  EC: [
    // Ground floor
    { id: 'G01',  floor: 'G', type: 'arena',     desc: 'Main arena floor (54,851 sf)' },
    { id: 'G02A', floor: 'G', type: 'room',      desc: 'Dressing room (162 sf)' },
    { id: 'G04A', floor: 'G', type: 'room',      desc: 'Visitor locker room (236 sf)' },
    { id: 'G04B', floor: 'G', type: 'room',      desc: 'Visitor locker room (236 sf)' },
    { id: 'G04C', floor: 'G', type: 'room',      desc: 'Home locker room (265 sf)' },
    { id: 'G07',  floor: 'G', type: 'room',      desc: 'Training room (556 sf)' },
    { id: 'G12',  floor: 'G', type: 'room',      desc: 'Training room (351 sf)' },
    { id: 'G15',  floor: 'G', type: 'room',      desc: 'Meeting room (399 sf)' },
    { id: 'G16',  floor: 'G', type: 'room',      desc: 'Meeting room (414 sf)' },
    { id: 'G18',  floor: 'G', type: 'room',      desc: 'Meeting room (401 sf)' },
    { id: 'G19',  floor: 'G', type: 'room',      desc: 'Commissary / service (793 sf)' },
    { id: 'G20',  floor: 'G', type: 'room',      desc: 'Athletic training room (1,900 sf)' },
    { id: 'G20B', floor: 'G', type: 'room',      desc: 'Hydrotherapy room (793 sf)' },
    { id: 'G24',  floor: 'G', type: 'room',      desc: 'Equipment room (636 sf)' },
    { id: 'G25',  floor: 'G', type: 'room',      desc: 'Laundry (364 sf)' },
    { id: 'G26',  floor: 'G', type: 'room',      desc: 'Office (2,046 sf)' },
    { id: 'G27',  floor: 'G', type: 'fitness',   desc: 'Strength training room (2,512 sf)' },
    { id: 'G28',  floor: 'G', type: 'room',      desc: 'Meeting room (558 sf)' },
    { id: 'G29',  floor: 'G', type: 'room',      desc: 'Boiler room (2,498 sf)' },
    { id: 'G30',  floor: 'G', type: 'room',      desc: 'Racquetball / softball batting (832 sf)' },
    { id: 'G31',  floor: 'G', type: 'room',      desc: 'Softball batting (237 sf)' },
    { id: 'G33',  floor: 'G', type: 'room',      desc: 'Tennis (229 sf)' },
    { id: 'G35',  floor: 'G', type: 'room',      desc: 'Storage (236 sf)' },
    { id: 'G39',  floor: 'G', type: 'room',      desc: 'Storage (1,705 sf)' },
    // First floor (mezzanine)
    { id: '100',  floor: '1', type: 'lounge',    desc: 'Athlete lounge (806 sf)' },
    { id: '100A', floor: '1', type: 'room',      desc: 'Meeting room (1,048 sf)' },
    { id: '101',  floor: '1', type: 'room',      desc: 'Reception (416 sf)' },
    { id: '102',  floor: '1', type: 'room',      desc: 'Meeting room (1,644 sf)' },
    { id: '103',  floor: '1', type: 'office',    desc: 'Office (113 sf)' },
    { id: '105',  floor: '1', type: 'office',    desc: 'Office (119 sf)' },
    { id: '107',  floor: '1', type: 'office',    desc: 'Office (109 sf)' },
    { id: '109',  floor: '1', type: 'office',    desc: 'Office (122 sf)' },
    { id: '111',  floor: '1', type: 'office',    desc: 'Office (112 sf)' },
    { id: '113',  floor: '1', type: 'office',    desc: 'Office (139 sf)' },
    { id: '115',  floor: '1', type: 'office',    desc: 'Office (164 sf)' },
    { id: '117',  floor: '1', type: 'office',    desc: 'Office (119 sf)' },
    { id: '119',  floor: '1', type: 'office',    desc: 'Office (120 sf)' },
    { id: '121',  floor: '1', type: 'office',    desc: 'Office (120 sf)' },
    { id: '125',  floor: '1', type: 'office',    desc: 'Office (120 sf)' },
    { id: '128',  floor: '1', type: 'room',      desc: 'Room (1,232 sf)' },
    { id: '131',  floor: '1', type: 'room',      desc: 'Room (133 sf)' },
    { id: '132',  floor: '1', type: 'room',      desc: 'Room (437 sf)' },
    { id: '140',  floor: '1', type: 'room',      desc: 'Storage (1,486 sf)' },
    { id: '142',  floor: '1', type: 'room',      desc: 'Room (1,791 sf)' },
    { id: '144',  floor: '1', type: 'room',      desc: 'Plumbing (448 sf)' },
    // Second floor (concourse)
    { id: '200',  floor: '2', type: 'concourse', desc: 'Main arena upper level (14,889 sf)' },
    { id: '200A', floor: '2', type: 'concourse', desc: 'Concourse (1,372 sf)' },
    { id: '203',  floor: '2', type: 'office',    desc: 'Athletic dept office (361 sf)' },
    { id: '203A', floor: '2', type: 'office',    desc: 'Athletic conference (170 sf)' },
    { id: '205',  floor: '2', type: 'office',    desc: 'Asst AD office (148 sf)' },
    { id: '206',  floor: '2', type: 'office',    desc: 'Asst AD office (152 sf)' },
    { id: '207',  floor: '2', type: 'office',    desc: 'AD office (126 sf)' },
    { id: '208',  floor: '2', type: 'office',    desc: 'Office (256 sf)' },
    { id: '209',  floor: '2', type: 'office',    desc: 'Work area (536 sf)' },
    { id: '210',  floor: '2', type: 'office',    desc: 'Concession (293 sf)' },
    { id: '211C', floor: '2', type: 'office',    desc: 'Media center (190 sf)' },
    { id: '214',  floor: '2', type: 'arena',     desc: 'Bearcat Den (2,341 sf)' },
    { id: '215',  floor: '2', type: 'room',      desc: 'Marketing room (148 sf)' },
    { id: '216',  floor: '2', type: 'room',      desc: 'Tickets (377 sf)' },
    { id: '230',  floor: '2', type: 'room',      desc: 'Sky box (310 sf)' },
    { id: '231',  floor: '2', type: 'room',      desc: 'Sky box (291 sf)' },
    { id: '232',  floor: '2', type: 'room',      desc: 'Master control room (296 sf)' },
  ],

  // ── Couper Administration (Bldg 029) ────────────────────────────────
  AD: [
    // Ground floor
    { id: 'G1',   floor: 'G', type: 'office',    desc: 'Office (385 sf)' },
    { id: 'G2',   floor: 'G', type: 'office',    desc: 'Office (164 sf)' },
    { id: 'G5',   floor: 'G', type: 'office',    desc: 'Office (409 sf)' },
    { id: 'G6',   floor: 'G', type: 'office',    desc: 'Office (211 sf)' },
    { id: 'G8',   floor: 'G', type: 'office',    desc: 'Office (477 sf)' },
    { id: 'G10',  floor: 'G', type: 'office',    desc: 'Office (391 sf)' },
    { id: 'G11',  floor: 'G', type: 'office',    desc: 'Office (556 sf)' },
    { id: 'G14',  floor: 'G', type: 'office',    desc: 'Office (792 sf)' },
    { id: 'G20',  floor: 'G', type: 'office',    desc: 'Office (106 sf)' },
    { id: 'G21',  floor: 'G', type: 'office',    desc: 'Office (164 sf)' },
    { id: 'G22',  floor: 'G', type: 'office',    desc: 'Office (147 sf)' },
    { id: 'G23',  floor: 'G', type: 'office',    desc: 'Office (266 sf)' },
    { id: 'G25',  floor: 'G', type: 'office',    desc: 'Large office (1,910 sf)' },
    { id: 'G34',  floor: 'G', type: 'office',    desc: 'Office (136 sf)' },
    { id: 'G35',  floor: 'G', type: 'office',    desc: 'University Police (518 sf)' },
    { id: 'G36',  floor: 'G', type: 'office',    desc: 'Office (195 sf)' },
    { id: 'G37',  floor: 'G', type: 'office',    desc: 'Office (199 sf)' },
    { id: 'G38',  floor: 'G', type: 'office',    desc: 'Office (228 sf)' },
    { id: 'G40',  floor: 'G', type: 'office',    desc: 'Office (205 sf)' },
    { id: 'G41',  floor: 'G', type: 'office',    desc: 'Office (236 sf)' },
    { id: 'G42',  floor: 'G', type: 'office',    desc: 'Office (285 sf)' },
    // First floor
    { id: '101',  floor: '1', type: 'office',    desc: 'Large office suite (625 sf)' },
    { id: '106',  floor: '1', type: 'office',    desc: 'Office (68 sf)' },
    { id: '108',  floor: '1', type: 'office',    desc: 'Office (349 sf)' },
    { id: '110',  floor: '1', type: 'office',    desc: 'Office (299 sf)' },
    { id: '111',  floor: '1', type: 'office',    desc: 'Office (168 sf)' },
    { id: '112',  floor: '1', type: 'office',    desc: 'Office (107 sf)' },
    { id: '113',  floor: '1', type: 'office',    desc: 'Office (112 sf)' },
    { id: '114',  floor: '1', type: 'office',    desc: 'Office (163 sf)' },
    { id: '115',  floor: '1', type: 'office',    desc: 'Office (100 sf)' },
    { id: '116',  floor: '1', type: 'office',    desc: 'Office (1,019 sf)' },
    { id: '118',  floor: '1', type: 'office',    desc: 'Office (605 sf)' },
    { id: '125',  floor: '1', type: 'office',    desc: 'Office (123 sf)' },
    { id: '127',  floor: '1', type: 'office',    desc: 'Office (215 sf)' },
    { id: '134',  floor: '1', type: 'office',    desc: 'Large office (899 sf)' },
    { id: '138',  floor: '1', type: 'office',    desc: 'Office (241 sf)' },
    { id: '141',  floor: '1', type: 'office',    desc: 'Office (354 sf)' },
    { id: '148',  floor: '1', type: 'office',    desc: 'Office (877 sf)' },
    // Second floor
    { id: '201',  floor: '2', type: 'office',    desc: "President's Office (477 sf)" },
    { id: '203',  floor: '2', type: 'office',    desc: 'Office (77 sf)' },
    { id: '205',  floor: '2', type: 'office',    desc: 'Office (134 sf)' },
    { id: '206',  floor: '2', type: 'office',    desc: 'Office (94 sf)' },
    { id: '207',  floor: '2', type: 'office',    desc: 'Office (98 sf)' },
    { id: '208',  floor: '2', type: 'office',    desc: 'Office (166 sf)' },
    { id: '209',  floor: '2', type: 'office',    desc: 'Office (131 sf)' },
    { id: '210',  floor: '2', type: 'office',    desc: 'Office (78 sf)' },
    { id: '211',  floor: '2', type: 'office',    desc: 'Office (164 sf)' },
    { id: '212',  floor: '2', type: 'office',    desc: 'Office (96 sf)' },
    { id: '213',  floor: '2', type: 'office',    desc: 'Office (97 sf)' },
    { id: '214',  floor: '2', type: 'office',    desc: 'Office (96 sf)' },
    { id: '217',  floor: '2', type: 'office',    desc: 'Large office (422 sf)' },
    { id: '220',  floor: '2', type: 'office',    desc: 'Office (362 sf)' },
    { id: '221',  floor: '2', type: 'office',    desc: 'Office (602 sf)' },
    { id: '225',  floor: '2', type: 'office',    desc: 'Office (266 sf)' },
    { id: '238',  floor: '2', type: 'office',    desc: 'Office (112 sf)' },
    { id: '240',  floor: '2', type: 'office',    desc: 'Office (157 sf)' },
    { id: '242',  floor: '2', type: 'office',    desc: 'Large office (2,246 sf)' },
    { id: '244',  floor: '2', type: 'office',    desc: 'Office (313 sf)' },
    { id: '245',  floor: '2', type: 'office',    desc: 'Office (385 sf)' },
    { id: '254',  floor: '2', type: 'office',    desc: 'Office (261 sf)' },
    { id: '255',  floor: '2', type: 'office',    desc: 'Office (162 sf)' },
    // Third floor
    { id: '301',  floor: '3', type: 'office',    desc: 'Office (376 sf)' },
    { id: '305',  floor: '3', type: 'office',    desc: 'Office (191 sf)' },
    { id: '306',  floor: '3', type: 'office',    desc: 'Office (127 sf)' },
    { id: '307',  floor: '3', type: 'office',    desc: 'Office (164 sf)' },
    { id: '308',  floor: '3', type: 'office',    desc: 'Office (228 sf)' },
    { id: '309',  floor: '3', type: 'office',    desc: 'Office (228 sf)' },
    { id: '310',  floor: '3', type: 'office',    desc: 'Office (198 sf)' },
    { id: '311',  floor: '3', type: 'office',    desc: 'Office (213 sf)' },
    { id: '312',  floor: '3', type: 'office',    desc: 'Office (264 sf)' },
    { id: '313',  floor: '3', type: 'office',    desc: 'Office (261 sf)' },
    { id: '314',  floor: '3', type: 'office',    desc: 'Office (131 sf)' },
    { id: '315',  floor: '3', type: 'office',    desc: 'Office (96 sf)' },
    // Fourth floor
    { id: '401',  floor: '4', type: 'office',    desc: 'Office (424 sf)' },
    { id: '403',  floor: '4', type: 'office',    desc: 'Office (71 sf)' },
    { id: '405',  floor: '4', type: 'office',    desc: 'Office (181 sf)' },
    { id: '406',  floor: '4', type: 'office',    desc: 'Office (96 sf)' },
    { id: '407',  floor: '4', type: 'office',    desc: 'Office (278 sf)' },
    { id: '408',  floor: '4', type: 'office',    desc: 'Office (134 sf)' },
    { id: '410',  floor: '4', type: 'office',    desc: 'Office (173 sf)' },
    { id: '411',  floor: '4', type: 'office',    desc: 'Office (183 sf)' },
    { id: '412',  floor: '4', type: 'office',    desc: 'Office (110 sf)' },
    { id: '413',  floor: '4', type: 'office',    desc: 'Office (198 sf)' },
    { id: '415',  floor: '4', type: 'office',    desc: 'Office (255 sf)' },
    { id: '418',  floor: '4', type: 'office',    desc: 'Office (154 sf)' },
    { id: '419',  floor: '4', type: 'office',    desc: 'Office (165 sf)' },
    { id: '420',  floor: '4', type: 'office',    desc: 'Office (204 sf)' },
    // Fifth floor
    { id: '501',  floor: '5', type: 'office',    desc: 'Office (380 sf)' },
    { id: '505',  floor: '5', type: 'office',    desc: 'Office (210 sf)' },
    { id: '506',  floor: '5', type: 'office',    desc: 'Office (89 sf)' },
    { id: '507',  floor: '5', type: 'office',    desc: 'Office (98 sf)' },
    { id: '508',  floor: '5', type: 'office',    desc: 'Office (322 sf)' },
    { id: '509',  floor: '5', type: 'office',    desc: 'Office (171 sf)' },
    { id: '510',  floor: '5', type: 'office',    desc: 'Office (197 sf)' },
    { id: '511',  floor: '5', type: 'office',    desc: 'Office (110 sf)' },
    { id: '512',  floor: '5', type: 'office',    desc: 'Office (956 sf)' },
    // Sixth floor
    { id: '601',  floor: '6', type: 'office',    desc: 'Office (417 sf)' },
    { id: '605',  floor: '6', type: 'office',    desc: 'Office (143 sf)' },
    { id: '606',  floor: '6', type: 'office',    desc: 'Office (334 sf)' },
    { id: '607',  floor: '6', type: 'office',    desc: 'Office (160 sf)' },
    { id: '609',  floor: '6', type: 'office',    desc: 'Office (199 sf)' },
    { id: '610',  floor: '6', type: 'office',    desc: 'Office (290 sf)' },
    { id: '612',  floor: '6', type: 'office',    desc: 'Office (91 sf)' },
    { id: '613',  floor: '6', type: 'office',    desc: 'Office (155 sf)' },
    { id: '614',  floor: '6', type: 'office',    desc: 'Office (171 sf)' },
  ],

  // ── Athletics — Gym East ────────────────────────────────────────────
  GE: [
    { id: 'N01',  floor: 'N', type: 'gym',       desc: 'Main gymnasium / basketball courts' },
    { id: 'N02',  floor: 'N', type: 'fitness',   desc: 'Cardio & weights fitness floor' },
    { id: 'N03',  floor: 'N', type: 'pool',      desc: 'Olympic-size swimming pool' },
    { id: '201',  floor: '2', type: 'court',     desc: 'Racquetball courts' },
    { id: '301',  floor: '3', type: 'office',    desc: 'Recreation Services admin' },
  ],

  // ── Anderson Center ─────────────────────────────────────────────────
  AC: [
    { id: 'N01',  floor: 'N', type: 'theater',   desc: 'Watters Theater (500-seat main stage)' },
    { id: 'N02',  floor: 'N', type: 'theater',   desc: 'Osterhout Concert Theater' },
    { id: '201',  floor: '2', type: 'theater',   desc: 'Chamber Hall (intimate recital space)' },
    { id: '301',  floor: '3', type: 'office',    desc: 'Theater & Music faculty offices' },
  ],

  // ── Science IV ──────────────────────────────────────────────────────
  S4: [
    { id: 'B01',  floor: 'B', type: 'lab',       desc: 'Basement lab' },
    { id: 'G01',  floor: 'G', type: 'lab',       desc: 'Ground floor lab' },
    { id: '101',  floor: '1', type: 'lab',       desc: 'First floor lab' },
    { id: '201',  floor: '2', type: 'lab',       desc: 'Second floor lab' },
    { id: '301',  floor: '3', type: 'lab',       desc: 'Third floor lab' },
  ],

  // ── Science V ───────────────────────────────────────────────────────
  S5: [
    { id: 'G01',  floor: 'G', type: 'lab',       desc: 'Ground floor lab' },
    { id: '101',  floor: '1', type: 'lab',       desc: 'First floor lab' },
    { id: '201',  floor: '2', type: 'lab',       desc: 'Second floor lab' },
  ],

  // ── Engineering & Science Building ─────────────────────────────────
  ES: [
    { id: 'G01',  floor: 'G', type: 'lab',       desc: 'Ground floor research lab' },
    { id: 'G02',  floor: 'G', type: 'lab',       desc: 'Ground floor teaching lab' },
    { id: '101',  floor: '1', type: 'classroom', desc: 'Classroom' },
    { id: '102',  floor: '1', type: 'classroom', desc: 'Classroom' },
    { id: '103',  floor: '1', type: 'lab',       desc: 'Computer lab' },
    { id: '104',  floor: '1', type: 'office',    desc: 'CS department office' },
    { id: '105',  floor: '1', type: 'office',    desc: 'CS faculty office' },
    { id: '106',  floor: '1', type: 'office',    desc: 'CS faculty office' },
    { id: '107',  floor: '1', type: 'office',    desc: 'CS faculty office' },
    { id: '108',  floor: '1', type: 'office',    desc: 'CS faculty office' },
    { id: '201',  floor: '2', type: 'lab',       desc: 'Research lab' },
    { id: '202',  floor: '2', type: 'lab',       desc: 'Advanced computing lab' },
    { id: '203',  floor: '2', type: 'office',    desc: 'Faculty office' },
    { id: '204',  floor: '2', type: 'office',    desc: 'Faculty office' },
    { id: '205',  floor: '2', type: 'office',    desc: 'Faculty office' },
    { id: '301',  floor: '3', type: 'lab',       desc: 'Graduate research lab' },
    { id: '302',  floor: '3', type: 'office',    desc: 'Faculty office' },
    { id: '303',  floor: '3', type: 'office',    desc: 'Faculty office' },
  ],
};

// Parse a search query into { code, roomQuery } if it looks like "EB N06"
export function parseRoomQuery(query) {
  const upper = query.trim().toUpperCase();
  for (const code of Object.keys(ROOMS)) {
    if (upper.startsWith(code)) {
      const rest = upper.slice(code.length).replace(/^[\s-]+/, '');
      if (rest) return { code, roomQuery: rest };
    }
  }
  return null;
}
